version: "3.7"

services:

  flask:
    build: ./flasky
    container_name: flasky
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginxy
    restart: always
    ports:
      - "8081:80"
